spring.application.name=StreamGo

#trabaja con Mysql
spring.datasource.url=jdbc:mysql://localhost:3306/StreamGo
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.open-in-view=false

#trabaja con railway ademas desconectar de las dependecias
#spring.datasource.password=QSyVhBsLQORBikmMLlvhJqlHENFjyMng
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=streamgo_secret_key_streamgo_secret_key_2026
jwt.expiration=86400000

#Mercad Pago
mercadopago.access.token=APP_USR-8960673039139422-052400-da7f81b3e0a229d07785eb03c88d2ad5-3422205730

# SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# LOGGING
spring.output.ansi.enabled=ALWAYS
logging.level.com.StreamGo=DEBUG
logging.level.org.springframework.security=INFO
logging.pattern.console=%n============================================================%n%d{yyyy-MM-dd HH:mm:ss} | %clr(%-5level) | %logger{30} | %msg%n
logging.file.name=logs/streamgo.log

# UPLOADS
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=3MB

# GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=905630454023-e7l6cmnn4q4ac49e89v2luqd7d2r21k5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
