spring.application.name=StreamGo

#trabaja con Mysql
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.open-in-view=false

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

#Mercad Pago
mercadopago.access.token=${MP_ACCESS_TOKEN}

# SWAGGER (controlado por env vars en produccion)
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:true}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:true}

# LOGGING
spring.output.ansi.enabled=ALWAYS
logging.level.com.StreamGo=DEBUG
logging.level.org.springframework.security=INFO
logging.pattern.console=%n============================================================%n%d{yyyy-MM-dd HH:mm:ss} | %clr(%-5level) | %logger{30} | %msg%n
logging.file.name=logs/streamgo.log

# UPLOADS
app.upload.dir=${UPLOAD_DIR:../uploads}
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=3MB

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB
spring.servlet.multipart.file-size-threshold=2MB
spring.servlet.multipart.location=./uploads


server.tomcat.connection-timeout=6000000
server.tomcat.max-swallow-size=10GB
server.tomcat.max-http-form-post-size=10GB

# GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# URL de tu servidor de archivos (la que te da ngrok)
# Configuración de archivos
file.upload-dir=D:/METADATA/file-server/Uploads
file.server.url=https://portsmouth-think-integrity-exhibits.trycloudflare.com
