name: StreamGo CI

on:
  pull_request:
    branches:
      - main
      - backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Entrar al backend
        run: cd StreamGo-backend

      - name: Dar permisos a Gradle
        run: chmod +x StreamGo-backend/gradlew

      - name: Compilar proyecto
        run: cd StreamGo-backend && ./gradlew build

  auto-merge:
    needs: build  # Solo se ejecuta si el build tiene éxito
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && success()
    steps:
      - name: Fusionar PR automáticamente
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'  # O 'merge' o 'rebase'
            })
